// Stable, allowlisted appearance IDs. Rendering metadata never changes gameplay.
export const AGENT_CATALOG = Object.freeze([
  {id:'ct-sas',team:'CT',name:'默认反恐精英 · SAS',englishName:'SAS',isDefault:true,model:'assets/characters-cs2/ct-sas.glb'},
  {id:'t-phoenix',team:'T',name:'默认恐怖分子 · 凤凰战士',englishName:'Phoenix',isDefault:true,model:'assets/characters-cs2/t-phoenix.glb'},
  {id:'ct-ava',team:'CT',name:'特别探员艾娃 · 联邦调查局',englishName:'Special Agent Ava | FBI',isDefault:false,model:'assets/characters-cs2/optional/ct-ava.glb'},
  {id:'t-miami',team:'T',name:'迈阿密达里尔爵士 · 专业人士',englishName:'Sir Bloody Miami Darryl | The Professionals',isDefault:false,model:'assets/characters-cs2/optional/t-miami.glb'},
  {id:"t-leet_variantg",team:"T",name:"地面叛军 | 精锐分子",englishName:"精锐分子",isDefault:false,model:"assets/characters-cs2/optional/t-leet_variantg.glb"},
  {id:"t-leet_varianth",team:"T",name:"奥西瑞斯 | 精锐分子",englishName:"精锐分子",isDefault:false,model:"assets/characters-cs2/optional/t-leet_varianth.glb"},
  {id:"t-leet_varianti",team:"T",name:"沙哈马特教授 | 精锐分子",englishName:"精锐分子",isDefault:false,model:"assets/characters-cs2/optional/t-leet_varianti.glb"},
  {id:"t-leet_variantf",team:"T",name:"精英穆哈里克先生 | 精锐分子",englishName:"精锐分子",isDefault:false,model:"assets/characters-cs2/optional/t-leet_variantf.glb"},
  {id:"t-leet_variantj",team:"T",name:"丛林反抗者 | 精锐分子",englishName:"精锐分子",isDefault:false,model:"assets/characters-cs2/optional/t-leet_variantj.glb"},
  {id:"t-phoenix_varianth",team:"T",name:"枪手 | 凤凰战士",englishName:"凤凰战士",isDefault:false,model:"assets/characters-cs2/optional/t-phoenix_varianth.glb"},
  {id:"t-phoenix_variantf",team:"T",name:"执行者 | 凤凰战士",englishName:"凤凰战士",isDefault:false,model:"assets/characters-cs2/optional/t-phoenix_variantf.glb"},
  {id:"t-phoenix_variantg",team:"T",name:"弹弓 | 凤凰战士",englishName:"凤凰战士",isDefault:false,model:"assets/characters-cs2/optional/t-phoenix_variantg.glb"},
  {id:"t-phoenix_varianti",team:"T",name:"街头士兵 | 凤凰战士",englishName:"凤凰战士",isDefault:false,model:"assets/characters-cs2/optional/t-phoenix_varianti.glb"},
  {id:"ct-fbi_variantf",team:"CT",name:"特种兵 | 联邦调查局（FBI）特警",englishName:"联邦调查局（FBI）特警",isDefault:false,model:"assets/characters-cs2/optional/ct-fbi_variantf.glb"},
  {id:"ct-fbi_variantg",team:"CT",name:"马尔库斯·戴劳 | 联邦调查局（FBI）人质营救队",englishName:"联邦调查局（FBI）人质营救队",isDefault:false,model:"assets/characters-cs2/optional/ct-fbi_variantg.glb"},
  {id:"ct-fbi_varianth",team:"CT",name:"迈克·赛弗斯 | 联邦调查局（FBI）狙击手",englishName:"联邦调查局（FBI）狙击手",isDefault:false,model:"assets/characters-cs2/optional/ct-fbi_varianth.glb"},
  {id:"ct-st6_variantk",team:"CT",name:"第三特种兵连 | 德国特种部队突击队",englishName:"德国特种部队突击队",isDefault:false,model:"assets/characters-cs2/optional/ct-st6_variantk.glb"},
  {id:"ct-st6_variante",team:"CT",name:"海豹突击队第六分队士兵 | 海军水面战中心海豹部队",englishName:"海军水面战中心海豹部队",isDefault:false,model:"assets/characters-cs2/optional/ct-st6_variante.glb"},
  {id:"ct-st6_variantg",team:"CT",name:"铅弹 | 海军水面战中心海豹部队",englishName:"海军水面战中心海豹部队",isDefault:false,model:"assets/characters-cs2/optional/ct-st6_variantg.glb"},
  {id:"ct-st6_variantm",team:"CT",name:"“两次”麦考伊 | 美国空军战术空中管制部队",englishName:"美国空军战术空中管制部队",isDefault:false,model:"assets/characters-cs2/optional/ct-st6_variantm.glb"},
  {id:"ct-st6_varianti",team:"CT",name:"海军上尉里克索尔 | 海军水面战中心海豹部队",englishName:"海军水面战中心海豹部队",isDefault:false,model:"assets/characters-cs2/optional/ct-st6_varianti.glb"},
  {id:"ct-st6_variantj",team:"CT",name:"“蓝莓” 铅弹 | 海军水面战中心海豹部队",englishName:"海军水面战中心海豹部队",isDefault:false,model:"assets/characters-cs2/optional/ct-st6_variantj.glb"},
  {id:"ct-st6_variantl",team:"CT",name:"“两次”麦考伊 | 战术空中管制部队装甲兵",englishName:"战术空中管制部队装甲兵",isDefault:false,model:"assets/characters-cs2/optional/ct-st6_variantl.glb"},
  {id:"ct-st6_variantn",team:"CT",name:"陆军中尉普里米罗 | 巴西第一营",englishName:"巴西第一营",isDefault:false,model:"assets/characters-cs2/optional/ct-st6_variantn.glb"},
  {id:"t-balkan_variantf",team:"T",name:"德拉戈米尔 | 军刀",englishName:"军刀",isDefault:false,model:"assets/characters-cs2/optional/t-balkan_variantf.glb"},
  {id:"t-balkan_varianti",team:"T",name:"马克西姆斯 | 军刀",englishName:"军刀",isDefault:false,model:"assets/characters-cs2/optional/t-balkan_varianti.glb"},
  {id:"t-balkan_variantg",team:"T",name:"准备就绪的列赞 | 军刀",englishName:"军刀",isDefault:false,model:"assets/characters-cs2/optional/t-balkan_variantg.glb"},
  {id:"t-balkan_variantj",team:"T",name:"黑狼 | 军刀",englishName:"军刀",isDefault:false,model:"assets/characters-cs2/optional/t-balkan_variantj.glb"},
  {id:"t-balkan_varianth",team:"T",name:"“医生”罗曼诺夫 | 军刀",englishName:"军刀",isDefault:false,model:"assets/characters-cs2/optional/t-balkan_varianth.glb"},
  {id:"t-balkan_variantk",team:"T",name:"红衫列赞 | 军刀",englishName:"军刀",isDefault:false,model:"assets/characters-cs2/optional/t-balkan_variantk.glb"},
  {id:"t-balkan_variantl",team:"T",name:"德拉戈米尔 | 军刀勇士",englishName:"军刀勇士",isDefault:false,model:"assets/characters-cs2/optional/t-balkan_variantl.glb"},
  {id:"ct-sas_variantf",team:"CT",name:"B 中队指挥官 | 英国空军特别部队",englishName:"英国空军特别部队",isDefault:false,model:"assets/characters-cs2/optional/ct-sas_variantf.glb"},
  {id:"ct-sas_variantg",team:"CT",name:"D 中队军官 | 新西兰特种空勤团",englishName:"新西兰特种空勤团",isDefault:false,model:"assets/characters-cs2/optional/ct-sas_variantg.glb"},
  {id:"ct-swat_variante",team:"CT",name:"指挥官 梅 “极寒” 贾米森 | 特警",englishName:"特警",isDefault:false,model:"assets/characters-cs2/optional/ct-swat_variante.glb"},
  {id:"ct-swat_variantf",team:"CT",name:"第一中尉法洛 | 特警",englishName:"特警",isDefault:false,model:"assets/characters-cs2/optional/ct-swat_variantf.glb"},
  {id:"ct-swat_variantg",team:"CT",name:"约翰 “范·海伦” 卡斯克 | 特警",englishName:"特警",isDefault:false,model:"assets/characters-cs2/optional/ct-swat_variantg.glb"},
  {id:"ct-swat_varianth",team:"CT",name:"生物防害专家 | 特警",englishName:"特警",isDefault:false,model:"assets/characters-cs2/optional/ct-swat_varianth.glb"},
  {id:"ct-swat_varianti",team:"CT",name:"军士长炸弹森 | 特警",englishName:"特警",isDefault:false,model:"assets/characters-cs2/optional/ct-swat_varianti.glb"},
  {id:"ct-swat_variantj",team:"CT",name:"化学防害专家 | 特警",englishName:"特警",isDefault:false,model:"assets/characters-cs2/optional/ct-swat_variantj.glb"},
  {id:"ct-swat_variantk",team:"CT",name:"中尉法洛（抱树人） | 特警",englishName:"特警",isDefault:false,model:"assets/characters-cs2/optional/ct-swat_variantk.glb"},
  {id:"t-professional_varf1",team:"T",name:"残酷的达里尔爵士（沉默）| 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_varf1.glb"},
  {id:"t-professional_varf2",team:"T",name:"残酷的达里尔爵士（头盖骨）| 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_varf2.glb"},
  {id:"t-professional_varf3",team:"T",name:"残酷的达里尔爵士（皇家）| 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_varf3.glb"},
  {id:"t-professional_varf4",team:"T",name:"残酷的达里尔爵士（聒噪）| 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_varf4.glb"},
  {id:"t-professional_varg",team:"T",name:"飞贼波兹曼 | 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_varg.glb"},
  {id:"t-professional_varh",team:"T",name:"小凯夫 | 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_varh.glb"},
  {id:"t-professional_vari",team:"T",name:"老K | 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_vari.glb"},
  {id:"t-professional_varj",team:"T",name:"出逃的萨莉 | 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_varj.glb"},
  {id:"t-professional_varf5",team:"T",name:"残酷的达里尔（穷鬼）| 专业人士",englishName:"专业人士",isDefault:false,model:"assets/characters-cs2/optional/t-professional_varf5.glb"},
  {id:"ct-gendarmerie_varianta",team:"CT",name:"军医少尉 | 法国宪兵特勤队",englishName:"法国宪兵特勤队",isDefault:false,model:"assets/characters-cs2/optional/ct-gendarmerie_varianta.glb"},
  {id:"ct-gendarmerie_variantb",team:"CT",name:"化学防害上尉| 法国宪兵特勤队",englishName:"法国宪兵特勤队",isDefault:false,model:"assets/characters-cs2/optional/ct-gendarmerie_variantb.glb"},
  {id:"ct-gendarmerie_variantc",team:"CT",name:"中队长鲁沙尔·勒库托 | 法国宪兵特勤队",englishName:"法国宪兵特勤队",isDefault:false,model:"assets/characters-cs2/optional/ct-gendarmerie_variantc.glb"},
  {id:"ct-gendarmerie_variantd",team:"CT",name:"准尉 | 法国宪兵特勤队",englishName:"法国宪兵特勤队",isDefault:false,model:"assets/characters-cs2/optional/ct-gendarmerie_variantd.glb"},
  {id:"ct-gendarmerie_variante",team:"CT",name:"军官雅克·贝尔特朗 | 法国宪兵特勤队",englishName:"法国宪兵特勤队",isDefault:false,model:"assets/characters-cs2/optional/ct-gendarmerie_variante.glb"},
  {id:"ct-diver_varianta",team:"CT",name:"指挥官黛维达·费尔南德斯（护目镜） | 海豹蛙人",englishName:"海豹蛙人",isDefault:false,model:"assets/characters-cs2/optional/ct-diver_varianta.glb"},
  {id:"ct-diver_variantb",team:"CT",name:"指挥官弗兰克·巴鲁德（湿袜） | 海豹蛙人",englishName:"海豹蛙人",isDefault:false,model:"assets/characters-cs2/optional/ct-diver_variantb.glb"},
  {id:"ct-diver_variantc",team:"CT",name:"中尉雷克斯·克里奇 | 海豹蛙人",englishName:"海豹蛙人",isDefault:false,model:"assets/characters-cs2/optional/ct-diver_variantc.glb"},
  {id:"t-jungle_raider_varianta",team:"T",name:"精锐捕兽者索尔曼 | 游击队",englishName:"游击队",isDefault:false,model:"assets/characters-cs2/optional/t-jungle_raider_varianta.glb"},
  {id:"t-jungle_raider_variantb",team:"T",name:"遗忘者克拉斯沃特 | 游击队",englishName:"游击队",isDefault:false,model:"assets/characters-cs2/optional/t-jungle_raider_variantb.glb"},
  {id:"t-jungle_raider_variantc",team:"T",name:"亚诺（野草） | 游击队",englishName:"游击队",isDefault:false,model:"assets/characters-cs2/optional/t-jungle_raider_variantc.glb"},
  {id:"t-jungle_raider_variantd",team:"T",name:"上校曼戈斯·达比西 | 游击队",englishName:"游击队",isDefault:false,model:"assets/characters-cs2/optional/t-jungle_raider_variantd.glb"},
  {id:"t-jungle_raider_variante",team:"T",name:"薇帕姐（革新派） | 游击队",englishName:"游击队",isDefault:false,model:"assets/characters-cs2/optional/t-jungle_raider_variante.glb"},
  {id:"t-jungle_raider_variantf",team:"T",name:"捕兽者（挑衅者） | 游击队",englishName:"游击队",isDefault:false,model:"assets/characters-cs2/optional/t-jungle_raider_variantf.glb"},
  {id:"t-jungle_raider_variantb2",team:"T",name:"克拉斯沃特（三分熟） | 游击队",englishName:"游击队",isDefault:false,model:"assets/characters-cs2/optional/t-jungle_raider_variantb2.glb"},
  {id:"t-jungle_raider_variantf2",team:"T",name:"捕兽者 | 游击队",englishName:"游击队",isDefault:false,model:"assets/characters-cs2/optional/t-jungle_raider_variantf2.glb"},
].map(agent=>Object.freeze(agent)));
export const DEFAULT_AGENT_IDS = Object.freeze(Object.fromEntries(AGENT_CATALOG.filter(agent=>agent.isDefault).map(agent=>[agent.team,agent.id])));
const byId=new Map(AGENT_CATALOG.map(agent=>[agent.id,agent]));
export function getAgent(id){return typeof id==='string'?byId.get(id):undefined;}
export function normalizeAgentLoadout(input={}){
  const value=input&&typeof input==='object'&&!Array.isArray(input)?input:{};
  return Object.fromEntries(Object.entries(DEFAULT_AGENT_IDS).map(([team,fallback])=>{
    const agent=getAgent(value[team]);return [team,agent?.team===team?agent.id:fallback];
  }));
}
